language: ruby
rvm:
  - 2.7.0
services:
  - postgresql
before_script:
  - psql -c 'create database curiosity_test;' -U postgres
  - rails db:migrate RAILS_ENV=test
env:
  global:
  - DB_HOST=localhost
  - DB_USER=postgres
  - DB_PASSWORD=
