language: ruby
rvm:
  - 2.7.1
  - jruby
services:
  - postgresql
before_script:
  - psql -c 'create database curiosity_test;' -U postgres
env:
  global:
  - DB_HOST=localhost
  - DB_USER=postgres
  - DB_PASSWORD=
